name: Build All Platforms

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: Sources
        run: npm install

      - name: Build Windows App
        working-directory: Sources
        run: npm run dist:win

      - name: Extract and Upload Windows Artifact
        run: |
          mkdir -p upload/windows
          cp Sources/dist/*.exe upload/windows/
        
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BinusLMS-Windows
          path: upload/windows/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: Sources
        run: npm install

      - name: Build Linux App
        working-directory: Sources
        run: npm run dist

      - name: Extract and Upload Linux Artifact
        run: |
          mkdir -p upload/linux
          cp Sources/dist/*.AppImage upload/linux/
          cp Sources/dist/*.deb upload/linux/
        
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BinusLMS-Linux
          path: upload/linux/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: Sources
        run: npm install

      - name: Build macOS App
        working-directory: Sources
        run: npm run dist:mac

      - name: Extract and Upload macOS Artifact
        run: |
          mkdir -p upload/macos
          cp Sources/dist/*.dmg upload/macos/
        
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BinusLMS-macOS
          path: upload/macos/