name: Build All Platforms

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Windows App
        run: npm run dist:win

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BinusLMS-Windows
          path: dist/*.exe
          compression-level: 6

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Linux App
        run: npm run dist

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BinusLMS-Linux
          path: |
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
          compression-level: 6

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build macOS App
        run: npm run dist:mac

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BinusLMS-macOS
          path: dist/*.dmg
          compression-level: 6

  merge-artifacts:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Artifacts
        uses: actions/download-artifact@v4
        with:
          name: BinusLMS-Windows
          path: combined-build/windows

      - name: Download Linux Artifacts
        uses: actions/download-artifact@v4
        with:
          name: BinusLMS-Linux
          path: combined-build/linux

      - name: Download macOS Artifacts
        uses: actions/download-artifact@v4
        with:
          name: BinusLMS-macOS
          path: combined-build/macos

      - name: Upload Combined Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BinusLMS-AllPlatforms
          path: combined-build/
          compression-level: 6